/*
 * @(#)VelocityLayoutServlet.java	2014-1-9
 */
package com.lotus.core;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * 描述当前类的作用
 * 
 * @author liyan
 * @version 2014-1-9
 * @since 1.0
 * @see
 */
public class VelocityLayoutServlet extends
		org.apache.velocity.tools.view.VelocityLayoutServlet
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8725856706909788473L;

	@Override
	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException
	{
		doRequest(request, response);
	}

	@Override
	public void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException
	{
		doGet(request, response);
	}

	@Override
	protected void doRequest(HttpServletRequest request,
			HttpServletResponse response) throws IOException
	{
		request.setAttribute("Request", request);
		request.setAttribute("ContextPath", request.getContextPath());
		request.setAttribute("BasePath",
				request.getScheme() + "://" + request.getServerName() + ":"
						+ request.getServerPort() + request.getContextPath());

		long runtime = System.currentTimeMillis();
		super.doRequest(request, response);

		if (request.getAttribute("close_comment") == null)
		{
			Date cur_time = Calendar.getInstance(request.getLocale()).getTime();
			PrintWriter pw = response.getWriter();
			pw.print("\r\n<!-- Generated by Nebula Server(");
			pw.print(cur_time);
			pw.print(") Cost ");
			pw.print(cur_time.getTime() - runtime);
			pw.print(" ms -->");
			pw.flush();
			pw.close();
		}
	}
}
