function iTreePersistence(){}var _p=iTreePersistence.prototype;_p.getExpanded=function(){return!1};_p.setExpanded=function(){};function iTreeCookie(){}_p=iTreeCookie.prototype;_p.setCookie=function(a,b,c){var d="";typeof c=="number"&&(d=new Date,d.setTime(d.getTime()+c*864E5),d="; expires="+d.toGMTString());document.cookie=a+"="+escape(b)+d+"; path=/"};_p.getCookie=function(a){a=RegExp("(;|^)[^;]*("+a+")=([^;]*)(;|$)").exec(document.cookie);return a!=null?unescape(a[3]):null};
_p.removeCookie=function(a){this.setCookie(a,"",-1)};function iTreeCookiePersistence(){this._openedMap={};this._cookies=new iTreeCookie;var a=this._cookies.getCookie(this.cookieName);if(a)for(var a=a.split("+"),b=a.length-1;b>=0;b--)this._openedMap[a[b]]=!0}_p=iTreeCookiePersistence.prototype=new iTreePersistence;_p.cookieName="fui-itree-cookie-persistence";_p.getExpanded=function(a){return a.id in this._openedMap};
_p.setExpanded=function(a,b){if(this.getExpanded(a)!=b){b?this._openedMap[a.id]=!0:delete this._openedMap[a.id];var c=[],d=0,e;for(e in this._openedMap)c[d++]=e;this._cookies.setCookie(this.cookieName,c.join("+"))}};var _iTreeArrayHelper={indexOf:function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return c;return-1},insertBefore:function(a,b,c){c=this.indexOf(a,c);c==-1?a.push(b):a.splice(c,0,b)},remove:function(a,b){var c=this.indexOf(a,b);c!=-1&&a.splice(c,1)}};
function _iTreeExtend(a,b){var c={},d;for(d in a)c[d]=a[d];for(var e in b)c[e]=b[e];return c}
var iTreeConfig={classes:{"I-line":"I-line","L-line":"L-line","L-minus":"L-minus","L-plus":"L-plus","T-line":"T-line","T-minus":"T-minus","T-plus":"T-plus",minus:"minus",plus:"plus",blank:"",openfolder:"fui-tree-openfolder-icon",folder:"fui-tree-folder-icon",leaf:"fui-tree-leaf-icon",loading:"fui-tree-loading-icon",error:"fui-tree-err-icon"},defaultText:" ",loadingText:"\u6b63\u5728\u52a0\u8f7d...",defaultAction:"javascript:void(0);",defaultBehavior:"classic",usePersistence:!1,setImagePath:function(){},
target:null,setTarget:function(a){iTreeConfig.target=a},cascadeChildCheck:!0,allChildCheckToParent:!1,allChildUnCheckToParent:!0,childUncheckCascadeToParent:!0,showNodeIcon:!0,checkEvent:!1,onTreeContext:!1},iTreeHandler={ie:/msie/i.test(navigator.userAgent),opera:/opera/i.test(navigator.userAgent),idCounter:0,idPrefix:"itreext-",checkboxPrefix:"itree-checkbox-",radioPrefix:"itree-radio-",getUniqueId:function(){return this.idPrefix+this.idCounter++},all:{},getNodeById:function(a){return this.all[a]},
addNode:function(a){this.all[a.id]=a},removeNode:function(a){delete this.all[a.id]},handleEvent:function(a){for(var b=a.target||a.srcElement;b!=null&&!this.all[b.id];)b=b.parentNode;if(b==null)return!1;b=this.all[b.id];if(typeof b["_on"+a.type]=="function")return b["_on"+a.type](a);return!1},contextMenu:function(a,b,c){if(iTreeConfig.onTreeContext&&typeof iTreeConfig.onTreeContext=="function")return iTreeConfig.onTreeContext(a,b,c),!1},dispose:function(){if(!this.disposed){for(var a in this.all)this.all[a].dispose();
this.disposed=!0}},htmlToText:function(a){return String(a).replace(/\s+|<([^>])+>|&amp;|&lt;|&gt;|&quot;|&nbsp;/gi,this._htmlToText)},_htmlToText:function(a){switch(a){case "&amp;":return"&";case "&lt;":return"<";case "&gt;":return">";case "&quot;":return'"';case "&nbsp;":return String.fromCharCode(160);default:if(/\s+/.test(a))return" ";if(/^<BR/gi.test(a))return"\n";return""}},textToHtml:function(a){return a},_textToHtml:function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";
case "\n":return"<BR>";case '"':return"&quot;";default:return"&nbsp;"}},persistenceManager:new iTreeCookiePersistence},iTreeProp={id:!1,type:"normal",name:"",value:"",text:"\u672a\u77e5\u8282\u70b9",tooltip:"",action:"javascript:void(0);",src:null,icon:"",openIcon:"",disabled:!1,checked:!1,target:!1};
function iTreeAbstractNode(a,b){this.childNodes=[];if(a)this.text=a;if(b)this.action=b;this.id=iTreeHandler.getUniqueId();if(iTreeConfig.usePersistence)this.open=iTreeHandler.persistenceManager.getExpanded(this);iTreeHandler.addNode(this)}_p=iTreeAbstractNode.prototype;_p._selected=!1;_p.indentWidth=18;_p.open=!1;_p.text=iTreeConfig.defaultText;_p.action=null;_p.target=null;_p.tooltip=null;_p._focused=!1;_p.doChecked=function(a,b,c){b==0?doRadioClick(this,a):b==1&&doCheckBoxClick(this,a);_stopEvent(c)};
_p.add=function(a,b){var c,d=this.childNodes.length==0,e=a.parentNode;if(b==null)e!=null&&e.remove(a),c=this.getLastChild(),this.childNodes.push(a);else{if(b.parentNode!=this)throw Error("Can only add nodes by it's parent and  between siblings");e!=null&&e.remove(a);_iTreeArrayHelper.insertBefore(this.childNodes,a,b)}if(b){if(b==this.firstChild)this.firstChild=a;a.previousSibling=b.previousSibling;b.previousSibling=a;a.nextSibling=b}else{if(!this.firstChild)this.firstChild=a;if(this.lastChild)this.lastChild.nextSibling=
a;a.previousSibling=this.lastChild;this.lastChild=a}a.parentNode=this;if(e=this.getTree())a.tree=e;var f=this.getDepth();if(f!=null)a.depth=f+1;if(this.getCreated()&&!e.getSuspendRedraw()){var f=this.getChildrenElement(),g=a.create(),h=b?b.getElement():null;f.insertBefore(g,h);c&&c.updateExpandIcon();d&&(this.setExpanded(this.getExpanded()),e&&e.getBehavior()!="classic"&&this.updateIcon())}return a};
_p.remove=function(a){if(arguments.length==0){if(this.parentNode)return this.parentNode.remove(this);return null}var b=this.getTree(),c=b?b.getSelected():null;if(c==a||a.contains(c))c.getFocused()?(this.select(),window.setTimeout('iTreeAbstractNode._onTimeoutFocus("'+this.id+'")',10)):this.select();if(a.parentNode!=this)throw Error("Can only remove children by it's parent!");_iTreeArrayHelper.remove(this.childNodes,a);if(this.lastChild==a)this.lastChild=a.previousSibling;if(this.firstChild==a)this.firstChild=
a.nextSibling;if(a.previousSibling)a.previousSibling.nextSibling=a.nextSibling;if(a.nextSibling)a.nextSibling.previousSibling=a.previousSibling;c=a.isLastSibling();a.parentNode=null;a.tree=null;a.depth=null;if(b&&this.getCreated()&&!b.getSuspendRedraw()){var b=this.getChildrenElement(),d=a.getElement();b.removeChild(d);c&&(c=this.getLastChild())&&c.updateExpandIcon();if(!this.hasChildren())b.style.display="none",this.updateExpandIcon(),this.updateIcon()}return a};
iTreeAbstractNode._onTimeoutFocus=function(a){iTreeHandler.all[a].focus()};_p.getId=function(){return this.id};_p.getTree=function(){throw Error("getTree called on Abstract Node");};_p.getDepth=function(){throw Error("getDepth called on Abstract Node");};_p.getCreated=function(){var a=this.getTree();return a&&a.rendered};_p.getParent=function(){return this.parentNode};_p.contains=function(a){if(a==null)return!1;if(a==this)return!0;return this.contains(a.parentNode)};
_p.getChildren=_p.getChildNodes=function(){return this.childNodes};_p.getFirstChild=function(){return this.childNodes[0]};_p.getLastChild=function(){return this.childNodes[this.childNodes.length-1]};_p.getPreviousSibling=function(){return this.previousSibling};_p.getNextSibling=function(){return this.nextSibling};_p.hasChildren=function(){return this.childNodes.length>0};_p.isLastSibling=function(){return this.nextSibling==null};
_p.findChildByText=function(a,b){b||(b=0);for(var c=a instanceof RegExp,d=0;d<this.childNodes.length;d++)if(c&&a.test(this.childNodes[d].getText())||this.childNodes[d].getText()==a){if(b==0)return this.childNodes[d];b--}return null};_p.findNodeByText=function(a,b){b||(b=0);if(a instanceof RegExp&&a.test(this.getText())||this.getText()==a){if(b==0)return this.childNodes[d];b--}for(var c,d=0;d<this.childNodes.length;d++)if(c=this.childNodes[d].findNodeByText(a,b))return c;return null};
_p.setId=function(a){var b=this.getElement();iTreeHandler.removeNode(this);this.id=a;if(b)b.id=a;iTreeHandler.addNode(this)};_p.isSelected=function(){return this._selected};_p.select=function(){this._setSelected(!0)};_p.deselect=function(){this._setSelected(!1)};
_p._setSelected=function(a){var b=this.getTree();if(b&&this._selected!=a){this._selected=a;var c=!1,d=b.getSelected();if(a&&d!=null&&d!=this){var e=b._fireChange,c=d._focused;b._fireChange=!1;d._setSelected(!1);b._fireChange=e}if(d=this.getRowElement())d.className=this.getRowClassName();a?(this._setTabIndex(b.tabIndex),b._selectedItem=this,b._fireOnChange(),b.setSelected(this),c&&this.focus()):this._setTabIndex(-1);b.getBehavior()!="classic"&&this.updateIcon()}};_p.getExpanded=function(){return this.open};
_p.setExpanded=function(a){var b;this.open=a;var c=this.getTree();if(this.hasChildren()){b=c?c.getSelected():null;!a&&this.contains(b)&&this.select();if(this.getElement()){if(b=this.getChildrenElement())b.style.display=a?"block":"none";if(b=this.getExpandIconElement())b.className="fui-tree-expand-icon "+this.getExpandIconClass()}iTreeConfig.usePersistence&&iTreeHandler.persistenceManager.setExpanded(this,a)}else if(b=this.getChildrenElement())b.style.display="none";c&&c.getBehavior()=="classic"&&
this.updateIcon()};_p.toggle=function(){this.setExpanded(!this.getExpanded())};_p.expand=function(){this.setExpanded(!0)};_p.collapse=function(){this.setExpanded(!1)};_p.collapseChildren=function(){for(var a=this.childNodes,b=0;b<a.length;b++)a[b].collapseAll()};_p.collapseAll=function(){this.collapseChildren();this.collapse()};_p.expandChildren=function(){for(var a=this.childNodes,b=0;b<a.length;b++)a[b].expandAll()};_p.expandAll=function(){this.expandChildren();this.expand()};
_p.reveal=function(){var a=this.getParent();a&&(a.setExpanded(!0),a.reveal())};_p.openPath=function(a,b,c){if(a=="")b&&this.select(),c&&window.setTimeout('iTreeAbstractNode._onTimeoutFocus("'+this.id+'")',10);else{var d=a.split("/"),e=d.slice(1).join("/"),d=this.getTree();if(a.charAt(0)=="/")if(d)d.openPath(e,b,c);else throw"Invalid path";else{this.setExpanded(!0);d=a.split("/");a=this.findChildByText(d[0]);if(!a)throw'Could not find child node with text "'+d[0]+'"';a.openPath(e,b,c)}}};
_p.focus=function(){};_p.getFocused=function(){return this._focused};_p._setTabIndex=function(a){var b=this.getLabelElement();b&&b.setAttribute("tabindex",a)};
_p.toHtml=function(){for(var a=[],b=this.childNodes,c=b.length,d=0;d<c;d++)a[d]=b[d].toHtml();b=this.getTree();a='<div class="fui-tree-children'+(!b.getShowLines()||b==this.parentNode&&!b.getShowRootLines()?"-nolines":"")+'" style="'+this.getLineStyle()+(this.getExpanded()&&this.hasChildren()?"":"display:none;")+'">'+a.join("")+"</div>";this.treeType.id&&this.setId(this.treeType.id);return'<div class="fui-tree-item" id="'+this.id+'"'+this.getEventHandlersHtml()+">"+this.getRowHtml()+a+"</div>"};
_p.getCheckboxHtml=function(){return'<input type="checkbox" id="'+(iTreeHandler.checkboxPrefix+this.id)+'" name="'+(this.treeType.name?this.treeType.name:"checkbox-"+this.id)+'" value="'+(this.treeType.value?this.treeType.value:"")+'" ondblclick="_stopEvent(event);" onclick="iTreeHandler.all[\''+this.id+"'].doChecked(this,1,event);\" "+(this.treeType.disabled?'disabled="disabled" ':"")+(this.treeType.checked?'checked="checked" ':"")+'class="fui-tree-checkbox" />'};
_p.getRadioHtml=function(){return'<input type="radio" id="'+(iTreeHandler.radioPrefix+this.id)+'" name="'+(this.treeType.name?this.treeType.name:"radio-"+this.id)+'"  value="'+(this.treeType.value?this.treeType.value:"")+'" ondblclick="_stopEvent(event);" onclick="iTreeHandler.all[\''+this.id+"'].doChecked(this,0,event);\" "+(this.treeType.disabled?' disabled="true" ':"")+(this.treeType.checked?' checked="true" ':"")+'class="fui-tree-radio" />'};
_p.getRowHtml=function(){this.getTree();var a="";this.treeType.type&&"checkbox"==this.treeType.type.toLowerCase()?a=this.getCheckboxHtml():this.treeType.type&&"radio"==this.treeType.type.toLowerCase()&&(a=this.getRadioHtml());return'<div class="'+this.getRowClassName()+'" style="padding-left:'+Math.max(0,(this.getDepth()-1)*this.indentWidth)+'px;">'+this.getExpandIconHtml()+a+this.getIconHtml()+this.getLabelHtml()+"</div>"};
_p.getRowClassName=function(){return"fui-tree-row"+(this.getDepth()==0?" fui-tree-root-row":"")+(this.isSelected()?" fui-tree-row-selected":"")+(this.action?"":" no-action")};
_p.getLabelHtml=function(){var a=!1,b=this.getTarget()?this.getTarget():iTreeConfig.target;if(this.treeType.target&&this.treeType.target!=null)b=this.treeType.target;this.treeType.tooltip&&(this.setToolTip(this.treeType.tooltip),a=this.getToolTip());return'<a href="'+iTreeHandler.textToHtml(this._getHref())+'" class="fui-tree-item-label" tabindex="-1"'+(a?' title="'+a+'"':"")+(b?' target="'+b+'"':"")+" oncontextmenu=\"iTreeHandler.contextMenu(this,'"+this.getId()+'\', event);return false;" onfocus="this.blur();">'+
this.getHtml()+"</a>"};_p._getHref=function(){return typeof this.action=="string"?this.action:"javascript:void(0);"};_p.getEventHandlersHtml=function(){return""};_p.getIconHtml=function(){var a=this.getIconSrc(),b=this.getTree().getShowNodeIcon();return a.indexOf(".")==-1?'<span class="fui-tree-icon '+a+'" style="'+(b?"":"display:none;")+'"></span>':'<span class="fui-tree-icon" style="background-image:url('+a+");"+(b?"":"display:none;")+'"></span>'};
_p.getIconSrc=function(){throw Error("getIconSrc called on Abstract Node");};_p.getExpandIconHtml=function(){return'<span class="fui-tree-expand-icon '+this.getExpandIconClass()+'"></span>'};
_p.getExpandIconClass=function(){var a=this.getTree(),b=!a.getShowLines()||a==this.parentNode&&!a.getShowRootLines();if(this.hasChildren()){var c=0;a&&a.getShowExpandIcons()&&(c=this.getExpanded()?2:1);a&&!b&&(c+=this.isLastSibling()?4:8);switch(c){case 1:return iTreeConfig.classes.plus;case 2:return iTreeConfig.classes.minus;case 4:return iTreeConfig.classes["L-line"];case 5:return iTreeConfig.classes["L-plus"];case 6:return iTreeConfig.classes["L-minus"];case 8:return iTreeConfig.classes["T-line"];
case 9:return iTreeConfig.classes["T-plus"];case 10:return iTreeConfig.classes["T-minus"];default:return iTreeConfig.classes.blank}}else return a&&b?iTreeConfig.classes.blank:this.isLastSibling()?iTreeConfig.classes["L-line"]:iTreeConfig.classes["T-line"]};_p.getLineStyle=function(){return"background-position:"+this.getLineStyle2()+";"};_p.getLineStyle2=function(){return(this.isLastSibling()?"-100":(this.getDepth()-1)*this.indentWidth)+"px 0"};_p.getElement=function(){return document.getElementById(this.id)};
_p.getRowElement=function(){var a=this.getElement();if(!a)return null;return a.firstChild};_p.getExpandIconElement=function(){var a=this.getRowElement();if(!a)return null;return a.firstChild};_p.getIconElement=function(){var a=this.getRowElement();if(!a)return null;return this.treeType.type=="normal"?a.childNodes[1]:a.childNodes[2]};_p.getLabelElement=function(){var a=this.getRowElement();if(!a)return null;return a.lastChild};
_p.getChildrenElement=function(){var a=this.getElement();if(!a)return null;return a.lastChild};_p.create=iTreeHandler.ie?function(){var a=document.createElement("div");a.style.display="none";document.body.appendChild(a);a.innerHTML=this.toHtml();var b=a.removeChild(a.firstChild);document.body.removeChild(a);return b}:function(){var a=document.createElement("div");a.innerHTML=this.toHtml();return a.removeChild(a.firstChild)};_p.setIcon=function(a){this.icon=a;this.getCreated()&&this.updateIcon()};
_p.getIcon=function(){return this.icon};_p.setOpenIcon=function(a){this.openIcon=a;this.getCreated()&&this.updateIcon()};_p.getOpenIcon=function(){return this.openIcon};_p.setText=function(a){this.setHtml(iTreeHandler.textToHtml(a))};_p.getText=function(){return iTreeHandler.htmlToText(this.getHtml())};_p.setHtml=function(a){this.text=a;var b=this.getLabelElement();if(b)b.innerHTML=a};_p.getHtml=function(){return this.text};_p.setTarget=function(a){this.target=a};_p.getTarget=function(){return this.target};
_p.setToolTip=function(a){this.tooltip=a;var b=this.getLabelElement();if(b)b.title=a};_p.getToolTip=function(){return this.tooltip};_p.setAction=function(a){this.action=a;if(a=this.getLabelElement())a.href=this._getHref();if(a=this.getRowElement())a.className=this.getRowClassName()};_p.getAction=function(){return this.action};
_p.update=function(){var a=this.getTree();if(!a.suspendRedraw){var b=this.getElement();if(b&&b.parentNode){var c=document.getElementById(iTreeHandler.checkboxPrefix+b.id);c||(c=document.getElementById(iTreeHandler.radioPrefix+b.id));var d=this.create();b.parentNode.replaceChild(d,b);if(c)document.getElementById(c.id).checked=c.checked,a.parentCheckedCascadeChild&&"checkbox"==c.type.toLowerCase()&&c.checked&&checkChildren(this,c.checked);(a=a.getSelected())&&a.getFocused()&&a.focus()}}};
_p.updateExpandIcon=function(){if(!this.getTree().suspendRedraw)this.getExpandIconElement().className="fui-tree-expand-icon "+this.getExpandIconClass(),this.getChildrenElement().style.backgroundPosition=this.getLineStyle2()};_p.updateIcon=function(){if(!this.getTree().suspendRedraw){var a=this.getIconElement(),b=this.getIconSrc();b.indexOf(".")==-1?a.className="fui-tree-icon "+b:a.style.backgroundImage="url("+b+")"}};
_p._callSuspended=function(a){var b=this.getTree(),c=b.getSuspendRedraw();b.setSuspendRedraw(!0);a.call(this);b.setSuspendRedraw(c)};
_p._onmousedown=function(a){if(/fui-tree-expand-icon/.test((a.target||a.srcElement).className)&&this.hasChildren())return this.toggle(),iTreeHandler.ie&&window.setTimeout('iTreeAbstractNode._onTimeoutFocus("'+this.id+'")',10),!1;this.select();iTreeHandler.opera||(iTreeHandler.ie?window.setTimeout('iTreeAbstractNode._onTimeoutFocus("'+this.id+'")',10):this.focus());if(a=this.getRowElement())a.className=this.getRowClassName();return!1};_p._onclick=function(){};
_p._onmouseover=function(a){a=a.target||a.srcElement;if(/fui-tree-expand-icon/.test(a.className)){var b=a.className.replace(/^\s+|\s+$/g,"").split(" ");if(b.length>1)a.className=a.className+" "+b[1]+"-hover"}};_p._onmouseout=function(a){a=a.target||a.srcElement;if(/fui-tree-expand-icon/.test(a.className)){var b=a.className.replace(/^\s+|\s+$/g,"").split(" ");if(b.length>1)a.className=a.className.replace(b[1]+"-hover","")}};
_p._ondblclick=function(a){(!/fui-tree-expand-icon/.test((a.target||a.srcElement).className)||!this.hasChildren())&&this.toggle()};_p._onfocus=function(){this.select();this._focused=!0};_p._onblur=function(){this._focused=!1};
_p._onkeydown=function(a){var b;b=!0;switch(a.keyCode){case 39:if(a.altKey){b=!0;break}this.hasChildren()&&(this.getExpanded()?this.getFirstChild().focus():this.setExpanded(!0));b=!1;break;case 37:if(a.altKey){b=!0;break}if(this.hasChildren()&&this.getExpanded())this.setExpanded(!1);else{b=this.getParent();var c=this.getTree();b&&(c.showRootNode||b!=c)&&b.focus()}b=!1;break;case 40:(b=this.getNextShownNode())&&b.focus();b=!1;break;case 38:(b=this.getPreviousShownNode())&&b.focus(),b=!1}!b&&a.preventDefault&&
a.preventDefault();return a.returnValue=b};_p._onkeypress=function(a){if(!a.altKey&&a.keyCode>=37&&a.keyCode<=40)return a.preventDefault&&a.preventDefault(),a.returnValue=!1};_p.dispose=function(){if(!this.disposed){for(var a=this.childNodes.length-1;a>=0;a--)this.childNodes[a].dispose();this.childNodes=this.parentNode=this.tree=null;this.disposed=!0}};_p.getLastShownDescendant=function(){if(!this.getExpanded()||!this.hasChildren())return this;return this.getLastChild().getLastShownDescendant()};
_p.getNextShownNode=function(){if(this.hasChildren()&&this.getExpanded())return this.getFirstChild();else{for(var a=this,b;a!=null;){b=a.getNextSibling();if(b!=null)return b;a=a.getParent()}return null}};_p.getPreviousShownNode=function(){var a=this.getPreviousSibling();if(a!=null)return a.getLastShownDescendant();var a=this.getParent(),b=this.getTree();if(!b.showRootNode&&a==b)return null;return a};
function iTree(a,b){var c=_iTreeExtend(iTreeProp,a||{});this.treeType=c;iTreeAbstractNode.call(this,c.text,c.action);if(c.icon)this.icon=c.icon;if(c.openIcon)this.openIcon=c.openIcon;if(b)this.behavior=b}_p=iTree.prototype=new iTreeAbstractNode;_p.indentWidth=18;_p.open=!0;_p._selectedItem=null;_p._fireChange=!0;_p.rendered=!1;_p.suspendRedraw=!1;_p.showLines=!0;_p.showExpandIcons=!0;_p.showRootNode=!0;_p.showRootLines=!0;_p.showNodeIcon=!0;_p.cascadeCheck=!0;_p.parentCheckedCascadeChild=!0;
_p.parentUncheckedCascadeChild=!0;_p.childCheckedCascadeParent=!0;_p.allChildCheckedCascadeParent=!1;_p.childUncheckedCascadeParent=!1;_p.allChildUncheckedCascadeParent=!0;_p.checkEvent=null;_p.animate=!1;_p.speed=200;_p.drag=!1;_p.getTree=function(){return this};_p.getDepth=function(){return 0};_p.getCreated=function(){return this.rendered};_p.loadData=function(datas){if(!datas||datas.length==0){return;}var t=null,i=0,len=datas.length;for(i=0;i<len;i++){t=datas[i];window["__itree_"+t.id]=new iTreeItem(t);}for(i=0;i<len;i++){t=datas[i];var pnode=t.pid?(window["__itree_"+t.pid]||this):this;pnode.add(window["__itree_"+t.id]);}};_p.setAnimate=function(a){this.animate=a};_p.getAnimate=function(){return this.animate};_p.setSpeed=function(a){this.speed=a};_p.getSpeed=function(){return this.speed};
_p.setDrag=function(a){this.drag=a};_p.getDrag=function(){return this.drag};_p.getExpanded=function(){return!this.showRootNode||iTreeAbstractNode.prototype.getExpanded.call(this)};_p.setExpanded=function(a){this.showRootNode?iTreeAbstractNode.prototype.setExpanded.call(this,a):this.open=a};_p.getExpandIconHtml=function(){return""};_p.getIconElement=function(){var a=this.getRowElement();if(!a)return null;return this.treeType.type=="normal"?a.firstChild:a.childNodes[1]};_p.getExpandIconElement=function(){return null};
_p.updateExpandIcon=function(){};_p.getRowClassName=function(){return iTreeAbstractNode.prototype.getRowClassName.call(this)+(this.showRootNode?"":" fui-tree-hide-root")};_p.getIconSrc=function(){var a=this.getTree()?this.getTree().getBehavior():iTreeConfig.defaultBehavior;if((a=a=="classic"&&this.getExpanded()||a!="classic"&&this.isSelected())&&this.openIcon)return this.openIcon;if(!a&&this.icon)return this.icon;return a?iTreeConfig.classes.openfolder:iTreeConfig.classes.folder};
_p.getEventHandlersHtml=function(){return'onmousedown="return iTreeHandler.handleEvent(event);" onmouseover="return iTreeHandler.handleEvent(event);" onmouseout="return iTreeHandler.handleEvent(event);" ondblclick="return iTreeHandler.handleEvent(event);" '};_p.setSelected=function(a){this._selectedItem!=a&&a&&a._setSelected(!0)};_p._fireOnChange=function(){if(this._fireChange&&typeof this.onchange=="function")this.onchange()};_p.getSelected=function(){return this._selectedItem};
_p.getTreeNodeById=function(a){return iTreeHandler.getNodeById(a)};_p.tabIndex="";_p.setTabIndex=function(a){var b=this._selectedItem||(this.showRootNode?this:this.firstChild);this.tabIndex=a;b&&b._setTabIndex(a)};_p.getTabIndex=function(){return this.tabIndex};_p.setBehavior=function(a){this.behavior=a};_p.getBehavior=function(){return this.behavior||iTreeConfig.defaultBehavior};_p.setShowLines=function(a){if(this.showLines!=a)this.showLines=a,this.rendered&&this.update()};_p.getShowLines=function(){return this.showLines};
_p.setShowNodeIcon=function(a){this.showNodeIcon=a};_p.getShowNodeIcon=function(){return this.showNodeIcon!=null?this.showNodeIcon:iTreeConfig.showNodeIcon};_p.setShowRootLines=function(a){if(this.showRootLines!=a)this.showRootLines=a,this.rendered&&this.update()};_p.getShowRootLines=function(){return this.showRootLines};_p.setShowExpandIcons=function(a){if(this.showExpandIcons!=a)this.showExpandIcons=a,this.rendered&&this.getTree().update()};_p.getShowExpandIcons=function(){return this.showExpandIcons};
_p.setShowRootNode=function(a){if(this.showRootNode!=a)this.showRootNode=a,this.rendered&&this.getTree().update()};_p.getShowRoootNode=function(){return this.showRootNode};_p.onchange=function(){};_p.create=function(){var a=iTreeAbstractNode.prototype.create.call(this);this.setTabIndex(this.tabIndex);this.rendered=!0;return a};_p.write=function(){if(arguments.length > 0){var arg = arguments[0];if(typeof arg === 'string') {arg = document.getElementById(arg);}if(arg && arg.nodeType === 1) {arg.innerHTML = this.toHtml();} else {document.write(this.toHtml());}} else {document.write(this.toHtml());}this.setTabIndex(this.tabIndex);this.rendered=!0};_p.setSuspendRedraw=function(a){this.suspendRedraw=a};
_p.getSuspendRedraw=function(){return this.suspendRedraw};function iTreeItem(a,b){var c=_iTreeExtend(iTreeProp,a||{});this.treeType=c;iTreeAbstractNode.call(this,c.text,c.action);if(c.icon)this.icon=c.icon;if(c.openIcon)this.openIcon=c.openIcon;b&&b.add(this)}_p=iTreeItem.prototype=new iTreeAbstractNode;_p.tree=null;_p.getDepth=function(){if(this.depth!=null)return this.depth;if(this.parentNode){var a=this.parentNode.getDepth();return this.depth=a!=null?a+1:null}return null};
_p.getTree=function(){if(this.tree)return this.tree;if(this.parentNode)return this.tree=this.parentNode.getTree();return null};_p.getCreated=function(){var a=this.getTree();return a&&a.getCreated()};
_p.getIconSrc=function(){var a=this.getTree()?this.getTree().getBehavior():iTreeConfig.defaultBehavior;if((a=a=="classic"&&this.getExpanded()||a!="classic"&&this.isSelected())&&this.openIcon)return this.openIcon;if(!a&&this.icon)return this.icon;if(this.hasChildren())return a?iTreeConfig.classes.openfolder:iTreeConfig.classes.folder;return iTreeConfig.classes.leaf};window.attachEvent&&window.attachEvent("onunload",function(){for(var a in iTreeHandler.all)iTreeHandler.all[a].dispose()});
function doCheckBoxClick(a,b){var c=a.getTree(),d=b.checked;c.cascadeCheck&&(d?(c.parentCheckedCascadeChild&&checkChildren(a,!0),(c.childCheckedCascadeParent||c.allChildCheckedCascadeParent)&&checkParents(a)):(c.parentUncheckedCascadeChild&&checkChildren(a,!1),(c.childUncheckedCascadeParent||c.allChildUncheckedCascadeParent)&&unCheckParents(a)));c.checkEvent&&typeof c.checkEvent=="function"?c.checkEvent.call(c,b,a):iTreeConfig.checkEvent&&typeof iTreeConfig.checkEvent=="function"&&iTreeConfig.checkEvent.call(c,
b,a)}function checkParents(a){var b=a.getTree(),a=a.parentNode;if(a instanceof iTreeAbstractNode){if(b.allChildCheckedCascadeParent&&!b.childCheckedCascadeParent)for(b=0;b<a.childNodes.length;b++){var c=_getTreeCheckboxObj(a.childNodes[b].id);if(c&&!c.checked&&!c.disabled)return}if((b=_getTreeCheckboxObj(a.id))&&!b.disabled)b.checked=!0;checkParents(a)}}
function unCheckParents(a){var b=a.getTree();if(b.childUncheckedCascadeParent&&!b.allChildUncheckedCascadeParent)for(b=a.parentNode;b instanceof iTreeAbstractNode;)if((a=_getTreeCheckboxObj(b.id))&&a.checked&&!a.disabled)a.checked=!1,b=b.parentNode;else break;else if(b.allChildUncheckedCascadeParent&&!b.childUncheckedCascadeParent&&(b=a.parentNode,b instanceof iTreeAbstractNode)){for(var c=0;c<b.childNodes.length;c++)if((a=_getTreeCheckboxObj(b.childNodes[c].id))&&a!=null&&a.checked&&!a.disabled)return!1;
if((a=_getTreeCheckboxObj(b.id))&&!a.disabled)a.checked=!1;unCheckParents(b)}}function checkChildren(a,b){if(a.childNodes.length>0){b&&a.expand();for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];if(d instanceof iTreeAbstractNode){checkChildren(d,b);var e=_getTreeCheckboxObj(d.id);if(!e)continue;if(!e.disabled)e.checked=b}delete d}}}function _getTreeCheckboxObj(a){if((a=document.getElementById(iTreeHandler.checkboxPrefix+a))&&a.type=="checkbox")return a;return null}
function doRadioClick(a,b){a.childNodes.length>0&&a.expand();var c=a.getTree();c.checkEvent&&typeof c.checkEvent=="function"?c.checkEvent.call(c,b,a):iTreeConfig.checkEvent&&typeof iTreeConfig.checkEvent=="function"&&iTreeConfig.checkEvent(b,a)}function _stopEvent(a){if(a=a||window.event)a.stopPropagation?a.stopPropagation():a.cancelBubble=!0};function iLoadTree(a,b){iTree.call(this,a,b);this.src=a.src;this.loading=!a.src;this.loaded=!a.src;this.errorText="";if(this.src)this._loadingItem=iLoadTree.createLoadingItem(),this.add(this._loadingItem),this.getExpanded()&&iLoadTree.loadXmlDocument(this)}iLoadTree.createLoadingItem=function(){return new iTreeItem({type:"normal",text:iTreeConfig.loadingText,icon:iTreeConfig.classes.loading,openIcon:iTreeConfig.classes.loading},null)};_p=iLoadTree.prototype=new iTree;
_p.setExpanded=function(a){iTree.prototype.setExpanded.call(this,a);this.src&&a&&!this.loaded&&!this.loading&&iLoadTree.loadXmlDocument(this)};function iLoadTreeItem(a,b){iTreeItem.call(this,a,b);this.src=a.src;this.loading=!a.src;this.loaded=!a.src;this.errorText="";if(this.src)this._loadingItem=iLoadTree.createLoadingItem(),this.add(this._loadingItem),this.getExpanded()&&iLoadTree.loadXmlDocument(this)}_p=iLoadTreeItem.prototype=new iTreeItem;
_p.setExpanded=function(a){iTreeItem.prototype.setExpanded.call(this,a);this.src&&a&&!this.loaded&&!this.loading&&iLoadTree.loadXmlDocument(this)};iLoadTree.prototype.load=_p.load=function(){this.setExpanded(!0)};
iLoadTree.prototype.reload=_p.reload=function(){if(this.loaded){var a=this.getTree(),b=this.getExpanded(),c=a.getSuspendRedraw();for(a.setSuspendRedraw(!0);this.childNodes.length>0;)this.remove(this.childNodes[this.childNodes.length-1]);this.loaded=!1;this._loadingItem=iLoadTree.createLoadingItem();this.add(this._loadingItem);b&&this.setExpanded(!0);a.setSuspendRedraw(c);this.update()}else this.open&&!this.loading?iLoadTree.loadXmlDocument(this):!this.open&&!this.loading&&this.setExpanded(!0)};
iLoadTree.prototype.setSrc=_p.setSrc=function(a){if(a!=this.src){var b=this.getExpanded();this._callSuspended(function(){for(;this.childNodes.length>0;)this.remove(this.childNodes[this.childNodes.length-1])});this.update();this.loading=this.loaded=!1;if(this._loadingItem)this._loadingItem.dispose(),this._loadingItem=null;if(this.src=a)this._loadingItem=iLoadTree.createLoadingItem(),this.add(this._loadingItem);this.setExpanded(b)}};iLoadTree.prototype.getSrc=_p.getSrc=function(){return this.src};
iLoadTree.prototype.dispose=function(){iTree.prototype.dispose.call(this);if(this._xmlHttp){this._xmlHttp.dispose&&this._xmlHttp.dispose();try{this._xmlHttp.onreadystatechange=null,this._xmlHttp.abort()}catch(a){}this._xmlHttp=null}};_p.dispose=function(){iTreeItem.prototype.dispose.call(this);if(this._xmlHttp){this._xmlHttp.dispose&&this._xmlHttp.dispose();try{this._xmlHttp.onreadystatechange=null,this._xmlHttp.abort()}catch(a){}this._xmlHttp=null}};
iLoadTree.prototype.openPath=_p.openPath=function(a,b,c){delete this._pathToOpen;this._selectPathOnLoad=b;this._focusPathOnLoad=c;if(a=="")b&&this.select(),c&&window.setTimeout('iTreeAbstractNode._onTimeoutFocus("'+this.getId()+'")',10);else{var d=a.split("/"),e=d.slice(1).join("/");if(a.charAt(0)=="/")this.getTree().openPath(e,b,c);else if(this.setExpanded(!0),this.loaded){d=a.split("/");a=this.findChildByText(d[0]);if(!a)throw'Could not find child node with text "'+d[0]+'"';a.openPath(e,b,c)}else this._pathToOpen=
a}};iLoadTree._attrs=["id","type","name","value","text","tooltip","src","action","target","icon","openIcon","disabled","checked"];
iLoadTree.createItemFromElement=function(a){var b={},c=a.attributes,d,e;e=c.length;for(d=0;d<e;d++)if(c[d]!=null)b[c[d].nodeName]=c[d].nodeValue;for(d=0;d<iLoadTree._attrs.length;d++)e=iLoadTree._attrs[d],(c=a.getAttribute(e))&&(b[e]=c);c=new iLoadTreeItem(b,null);b.text&&c.setText(b.text);if(b.target)c.target=b.target;b.id&&c.setId(b.id);if(b.tooltip)c.tooltip=b.tooltip;b.expanded&&c.setExpanded(b.expanded!="false");if(b.onload)c.onload=new Function(b.onload);if(b.onerror)c.onerror=new Function(b.onerror);
c.attributes=b;a=a.childNodes;e=a.length;for(d=0;d<e;d++)a[d].tagName=="tree"&&c.add(iLoadTree.createItemFromElement(a[d]));return c};iLoadTree.loadXmlDocument=function(a){if(!a.loading&&!a.loaded){a.loading=!0;var b=a.getId();a._xmlHttp=window.XMLHttpRequest?new XMLHttpRequest:new window.ActiveXObject("Microsoft.XmlHttp");a._xmlHttp.open("GET",a.src,!0);a._xmlHttp.onreadystatechange=new Function('iLoadTree._onload("'+b+'")');window.setTimeout('iLoadTree._ontimeout("'+b+'")',10)}};
iLoadTree._onload=function(a){a=iTreeHandler.all[a];if(a._xmlHttp.readyState==4)iLoadTree.documentLoaded(a),iLoadTreeQueue.remove(a),a._xmlHttp.dispose&&a._xmlHttp.dispose(),a._xmlHttp=null};iLoadTree._ontimeout=function(a){iLoadTreeQueue.add(iTreeHandler.all[a])};
iLoadTree.documentLoaded=function(a){if(!a.loaded){a.errorText="";a.loaded=!0;a.loading=!1;var b=a.getTree(),c=b.getSuspendRedraw();b.setSuspendRedraw(!0);var d=a._xmlHttp.responseXML;if(!d||d.parserError&&d.parseError.errorCode!=0||!d.documentElement)a.errorText=!d||d.parseError.errorCode==0?"\u52a0\u8f7d\u5931\u8d25\uff1a"+a.src+" ("+a._xmlHttp.status+": "+a._xmlHttp.statusText+")":"\u52a0\u8f7d\u5931\u8d25\uff1a"+a.src+" ("+d.parseError.reason+")";else for(var e=0,d=d.documentElement.childNodes,
f=d.length,g=0;g<f;g++)d[g].tagName=="tree"&&(a.add(iLoadTree.createItemFromElement(d[g])),e++);if(a.errorText!=""){if(a._loadingItem.icon=iTreeConfig.classes.error,a._loadingItem.text=a.errorText,a._loadingItem.action=iLoadTree._reloadParent,a._loadingItem.tooltip="\u53cc\u51fb\u8282\u70b9\u91cd\u65b0\u52a0\u8f7d",b.setSuspendRedraw(c),a._loadingItem.update(),typeof a.onerror=="function")a.onerror()}else if(a._loadingItem!=null&&a.remove(a._loadingItem),a._pathToOpen&&a.openPath(a._pathToOpen,a._selectPathOnLoad,
a._focusPathOnLoad),b.setSuspendRedraw(c),a.update(),typeof a.onload=="function")a.onload()}};iLoadTree._reloadParent=function(){this.getParent().reload()};
var iLoadTreeQueue={_nodes:[],_ie:/msie/i.test(navigator.userAgent),_opera:/opera/i.test(navigator.userAgent),add:function(a){this._ie||this._opera?(this._nodes.push(a),this._nodes.length==1&&this._send()):a._xmlHttp.send(null)},remove:function(a){if(this._ie||this._opera)_iTreeArrayHelper.remove(this._nodes,a),this._nodes.length>0&&this._send()},_send:function(){var a=this._nodes[0].getId();(a=iTreeHandler.all[a])&&(a._xmlHttp?a._xmlHttp.send(null):this.remove(a))}};
